// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {context} from '../models';

export function Close():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function NewMenu():Promise<menu.Menu>;

export function PrintGreet(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
