// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['service']['App']['Close']();
}

export function Greet(arg1) {
  return window['go']['service']['App']['Greet'](arg1);
}

export function NewMenu() {
  return window['go']['service']['App']['NewMenu']();
}

export function PrintGreet(arg1) {
  return window['go']['service']['App']['PrintGreet'](arg1);
}

export function SelectFile(arg1, arg2) {
  return window['go']['service']['App']['SelectFile'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['service']['App']['SetContext'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['App']['Startup'](arg1);
}
