// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStats():Promise<{[key: string]: any}>;

export function SetByteCount(arg1:number):Promise<void>;

export function SetImageCount(arg1:number):Promise<void>;

export function SetTimeCount(arg1:number):Promise<void>;

export function WailsInit():Promise<void>;
