// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clear():Promise<void>;

export function Convert():Promise<Array<Error>>;

export function HandleFile(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function WailsInit():Promise<void>;
