// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Close():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function PrintGreet(arg1:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;
